<?php
// $Id: flag_terms.module,v 1.2 2009/11/19 13:09:02 tayzlor Exp $
/**
 * @file
 * Flag Terms.
 * Written by Graham Taylor.
 */

module_load_include('inc', 'flag_webform_submissions', 'flag_webform_submissions');

/**
 * Implementation of hook_flag_definitions().
 */
function flag_webform_submissions_flag_definitions() {
  return array(
    'submission' => array(
      'title' => t('Webform submissions'),
      'description' => t('Webform submissions are used to collect informatino.'),
      'handler' => 'flag_webform_submissions',
    ),
  );
}

/**
 * Implementation of template_preprocess_page().
 */
function flag_webform_submissions_preprocess_page(&$variables) {
  if (in_array('page-node', $variables['template_files'])) {
    $node = explode('-', $variables['template_files'][1]);
    $nid = $node[2];
  }

  if (in_array('page-node-submission', $variables['template_files'])) {
    $submission = explode('-', $variables['template_files'][3]);
    $sid = $submission[3];
  }

  // submission page
  if (is_numeric($nid) && is_numeric($sid)) {
    $variables = theme('flag_webform_submissions_flags', $nid, $sid, $variables);
  }

  // submission list page
  if (in_array('page-node-webform-results', $variables['template_files'])) {
    $variables = theme('flag_webform_submissions_flags', $nid, 'list', $variables);
  }

}

/**
 * Implementation of hook_theme()
 */
function flag_webform_submissions_theme() {
  return array(
    'flag_webform_submissions_flags' => array(
      'arguments' => array('nid' => NULL, 'sid' => NULL, 'variables' => NULL),
    ),
  );
}

/**
 * Theme function to inject flag links into node/%/submission/% pages.
 */
function theme_flag_webform_submissions_flags($nid, $sid, $variables) {
  $links = array();
  foreach (flag_get_flags('submission') as $flag) {
    if ($flag->show_on_submissions_page != 0) {
      // have to join the nid and sid together due to the flag cacheing mechanism
      $links[] = flag_create_link($flag->name, $sid . '-' . $nid);
    }
  }
  $variables['content'] = join('', $links) . $variables['content'];

  return $variables;
}

function flag_webform_submissions_preprocess_webform_results_submissions(&$vars) {
  // generate flag links
  $flags_used = array();
  foreach (flag_get_flags('submission') as $flag) {
    foreach($vars['table']['#rows'] as $id => $row) {
      // have to join the nid and sid together due to the flag cacheing mechanism
      $flag_code = flag_create_link($flag->name, $row[0] . '-' . $vars['node']->nid);
      $vars['table']['#rows'][$id][] = $flag_code;

      // keep track of which flags were used so we can build headers
      if ($flag_code) $flags_used[$flag->name] = true;
    }
  }
  
  // Add flag headers in
  foreach (flag_get_flags('submission') as $flag) {
    if (array_key_exists($flag->name, $flags_used)) 
      $vars['table']['#header'][] = array('data' => $flag->title, 'field' => $flag->name);
  }
}